name: LSIF

on:
  push:
    branches:
      - main

jobs:
  lsif-dotnet:
    runs-on: ubuntu-latest
    container: ghcr.io/tcz717/lsifdotnet:main
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Restore dependencies
        run: dotnet restore
      - run: mkdir lsif_index
      - name: Generate LSIF data
        run: /app/lsif-dotnet --output lsif_index/index.lsif
      - name: Publish LSIF
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: lsif-index
          FOLDER: lsif_index
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}